/**
 * HandoffSummary — Deterministic handoff doc generator
 * No AI call — built from stored project data + notes.
 */

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FileText, Copy, Check, X } from "lucide-react";
import { formatDate } from "@/lib/utils";
import type { Project, ProjectNote } from "../../shared/schema";

interface Props {
  project: Project;
  notes: ProjectNote[];
}

function generateHandoff(project: Project, notes: ProjectNote[]): string {
  const p = project as Project & { healthEndpointUrl?: string; lastHealthStatus?: string; nextAction?: string };
  const blockerNotes = notes.filter(n => n.severity === "blocker" || n.severity === "critical");
  const warningNotes = notes.filter(n => n.severity === "warning");
  const infoNotes    = notes.filter(n => n.severity === "info");
  const now = new Date().toISOString().split("T")[0];

  const lines: string[] = [
    `# Project Handoff — ${project.name}`,
    `Generated: ${now}`,
    ``,
    `## Current Status`,
    `- Status: ${project.status.toUpperCase()}`,
    `- Priority: ${project.priority.toUpperCase()}`,
    `- Production Stage: ${project.productionStage}`,
    `- Last Deployed: ${project.lastDeployedAt ? formatDate(project.lastDeployedAt) : "Never"}`,
    ``,
    `## Infrastructure`,
    `- Domain: ${project.domain ?? "Not set"}`,
    `- Railway URL: ${project.railwayUrl ?? "Not set"}`,
    `- GitHub: ${project.githubUrl ?? "Not set"}`,
    `- Health Endpoint: ${p.healthEndpointUrl ?? "Not configured"}`,
    `- Last Health Status: ${p.lastHealthStatus ?? "unknown"}`,
    ``,
    `## Integrations`,
    `- Stripe: ${project.stripeConnected ? "Connected" : "Not connected"}`,
    `- Clerk Auth: ${project.clerkConnected ? "Connected" : "Not connected"}`,
    `- AI Enabled: ${project.aiEnabled ? "Yes" : "No"}`,
    ``,
  ];

  if (blockerNotes.length > 0) {
    lines.push(`## Active Blockers (${blockerNotes.length})`);
    for (const n of blockerNotes) {
      lines.push(`### ${n.title}`);
      lines.push(n.note);
      lines.push(``);
    }
  }

  if (project.blockers) {
    lines.push(`## Recorded Blockers`);
    lines.push(project.blockers);
    lines.push(``);
  }

  if (warningNotes.length > 0) {
    lines.push(`## Warnings (${warningNotes.length})`);
    for (const n of warningNotes) {
      lines.push(`- [${n.title}] ${n.note}`);
    }
    lines.push(``);
  }

  if (infoNotes.length > 0) {
    lines.push(`## Recent Operational Notes`);
    for (const n of infoNotes.slice(0, 5)) {
      lines.push(`- ${n.title}: ${n.note}`);
    }
    lines.push(``);
  }

  if (project.notes) {
    lines.push(`## Project Notes`);
    lines.push(project.notes);
    lines.push(``);
  }

  lines.push(`## Next Recommended Action`);
  if (p.nextAction) {
    lines.push(p.nextAction);
  } else if (blockerNotes.length > 0) {
    lines.push(`Resolve active blockers before proceeding. See Blockers section above.`);
  } else if (project.productionStage === "idea") {
    lines.push(`Begin Phase 0 Pre-Flight: gather secrets, define env vars, create PHASE-0-handoff.md`);
  } else if (project.productionStage === "prototype") {
    lines.push(`Complete core features and move to beta. Set up Railway deploy.`);
  } else if (project.productionStage === "beta") {
    lines.push(`Run full verification pass. Set up production env vars. Move to live.`);
  } else if (project.productionStage === "live") {
    lines.push(`Monitor health endpoint. Ensure all env vars are set. Review operational notes.`);
  } else {
    lines.push(`Review current blockers and operational notes. Update status as needed.`);
  }

  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by Claytara Command — Mission Control`);

  return lines.join("\n");
}

export function HandoffSummary({ project, notes }: Props) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const text = generateHandoff(project, notes);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!open) {
    return (
      <Button variant="outline" size="sm" onClick={() => setOpen(true)} className="gap-2">
        <FileText className="h-3.5 w-3.5" />
        Generate Handoff
      </Button>
    );
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="w-full max-w-2xl max-h-[85vh] flex flex-col rounded-2xl bg-card border border-border shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-border shrink-0">
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-muted-foreground" />
            <p className="font-semibold text-sm text-foreground">Handoff Summary — {project.name}</p>
          </div>
          <div className="flex items-center gap-2">
            <Button size="sm" variant="outline" onClick={handleCopy} className="gap-1.5 text-xs">
              {copied ? <Check className="h-3 w-3 text-green-400" /> : <Copy className="h-3 w-3" />}
              {copied ? "Copied!" : "Copy"}
            </Button>
            <button onClick={() => setOpen(false)} className="text-muted-foreground hover:text-foreground">
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>
        {/* Content */}
        <div className="flex-1 overflow-y-auto p-5">
          <pre className="text-xs text-foreground font-mono leading-relaxed whitespace-pre-wrap break-words bg-background rounded-lg p-4 border border-border">
            {text}
          </pre>
        </div>
      </div>
    </div>
  );
}
